[package]
name = "notify"
version = "0.1.0"
edition = "2021"
author = "Coombszy LCCoombs@hotmail.com"

[dependencies]
# JSON Serialization
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"