[config]
# Connection to IFTTT, Checkout the IFTTT Docs (https://ifttt.com/maker_webhooks)
# key: Webhooks API key.
# event: Event trigger name in applet.
ifttt_key = "WEBHOOKKEY"
ifttt_event = "notification_phone"

# Scheduled notifications control
# schedule_enabled: enable reading and sending scheduled notifications.
# scheduled_notifications: source json to read notifications from.
schedule_enabled = true
schedule_source = "./data/notifications.json"

# Web Server control
# web_enabled: enable web server to receive on demand notifications.
# web_port: port to listen on.
web_enabled = true
web_port = 8080

# Application log output
# write_logs: enable writing to a log file.
# write_logs_dir: 
write_logs = true # NOT IMPL
write_logs_dir = "./data/notify.log" # NOT IMPL
